
project_id = "rlbzkgnvuufvlnmdckno"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[edge_functions]
enabled = true
port = 54323

[functions.create-checkout]
verify_jwt = true

[functions.submit-crypto-proof]
verify_jwt = true
